[build]
buildCommand = "pnpm install --frozen-lockfile --prod=false && VITE_NETWORK=${VITE_NETWORK:-mainnet} VITE_BACKEND_URL=${VITE_BACKEND_URL:-https://api.govex.ai} pnpm build"

[deploy]
startCommand = "serve dist -s -c ../serve.json -l tcp://0.0.0.0:${PORT:-3000}"
